import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import React from 'react'

import { DARK_TOKENS, LIGHT_TOKENS } from '@/constants'
import clsx from 'clsx'

import SiteFooter from '../components/SiteFooter'
import SiteHeader from '../components/SiteHeader'

import './globals.css'

// TODO: フォントが適用できない問題
const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const theme = 'light'

  return (
    <html
      lang='ja'
      className={clsx(notoSansJP.variable, 'font-sans')}
      data-color-theme={theme}
      // @ts-ignore
      style={theme === 'light' ? LIGHT_TOKENS : DARK_TOKENS}
    >
      <body className='bg-dots'>
        <SiteHeader />
        <div className='site-wrapper bg-white'>{children}</div>
        <SiteFooter />
      </body>
    </html>
  )
}
