import type { Metadata } from 'next'
import React from 'react'

import SiteFooter from '../components/SiteFooter'
import SiteHeader from '../components/SiteHeader'

import GetScrollBarWidth from '@/components/GetScrollBarWidth'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <GetScrollBarWidth>
      <html lang='ja' className='font-sans'>
        <body>
          <SiteHeader />
          <div className='site-wrapper'>{children}</div>
          <SiteFooter />
        </body>
      </html>
    </GetScrollBarWidth>
  )
}
